# Generated by Django 4.0.4 on 2022-05-26 12:50

from django.db import migrations, models
import general.models.titles


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_socialmedia_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='titles',
            name='background',
            field=models.ImageField(null=True, upload_to=general.models.titles.get_file_path),
        ),
    ]
