# Generated by Django 4.0.4 on 2022-05-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleworks', '0002_ido_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='ido',
            name='icon',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
